### ISSUE TITLE
S3 integration - remove old versions

### ISSUE THREAD

**Issue by androane** [owais/django-webpack-loader#149]
If I previously generated `main-a.js` and uploaded it to S3, and now I do some modifications and I end up with a different static file like `main-b.js`, how to I tell S3 to remove `main-a.js` after I upload `main-b.js`?

**Comment by KyeRussell** [comment]
This can be accomplished with a webpack plugin and is outside of the Django
loader’s domain.

https://github.com/johnagan/clean-webpack-plugin

**Comment by owais** [comment]
If you are publishing to S3 using Django's staticfiles system then check how it can be configured to remove outdated assets. @KyeRussell already shared one plugin for webpack if you want to handle it there. 

I personally generate assets so that they are stored in sub-directories. That way I can write scripts to remove entire sub-directories older than the latest 2.
