### ISSUE TITLE
Issues experienced

### ISSUE THREAD

**Issue by markfinger** [owais/django-webpack-loader#5]
Hey @owais 

Your project's definitely appealing - having written far too many python wrappers in my time, there's definitely got to be a better way. While I've generally tried to keep things as minimalistic as possible, the disconnect between processes makes it extremely difficult to maintain a small footprint. The lack of an easily understandable codebase results in wrapper APIs which lag behind the core and overly complicate build processes.

I haven't really mused over it yet, but I'm curious do you have any reflections regarding your approach? Any identified issues, etc?

**Comment by owais** [comment]
Hey Mark,

I've not faced any major issues with this approach yet but I've still not switched my big projects completely to this library. I've only been able to test this with newly created small projects so I think it'll be a while before I run into any complex issues.

One minor annoyance is that you've to manually manage the webpack process but to me it is completely worth it given how much flexibility it comes with. Another limitation right now is that it'll only report 1 error at a time. webpack-bundle-tracker will dump the first error to the stats file and django will raise that as an WebpackException so it can be noticed in the browser. The error may not always show the exact problem but in my experience it has been a good enough. I just want django to let me know when I should check on webpack. It doesn't have to tell me exactly what is wrong.

Also, sometimes when you start working after a break and django will read the already present stats file and serve the old bundles if you forget to run webpack. This can be confusing as your changes to JS/CSS will not show up and django will not tell you to run webpack as it assumes webpack has done it's job because stats file is present. I'd like to solve this some time soon.

Make sure you don't store the stats file as a static asset. Right now, output of the file is not cached and it is read on every request. If you store it as a static asset and sync to s3, it'll be quite costly to read it on every request. An upcoming version will cache the stats file so it is read only once.

Personally, I haven't run into any major integration issues but I think this approach will be frustrating for people who don't know or don't want to deal with Javascript.

**Comment by markfinger** [comment]
> webpack-bundle-tracker will dump the first error to the stats file and django will raise that as an WebpackException so it can be noticed in the browser.

Yeah, one thing I like about hmr is that it logs every error and warning produced. It might be worth serializing every error and then just spitting out an exception with "Webpack errors: ['...', '...']". Also, I've generally found that you can just use the error's `stack` property, it's something like `<type>: <message> <stack>`, but you'd prob need to check if it's an instance of error or just a string.

> sometimes when you start working after a break and django will read the already present stats file and serve the old bundles

The stats object should have a [fileDependencies array](https://github.com/markfinger/webpack-wrapper/blob/master/lib/Wrapper.js#L159) which lists every file. When I'm relying on cached content, I've been checking mtimes on every file before serving it up. If the config file or any deps have changed since the compilation, the cache throws errors and the wrapper blocks until the compiler's finished. [This](https://github.com/markfinger/webpack-wrapper/blob/master/lib/Cache.js#L54-L75) is a JS implementation, but it'd be pretty easy to do in python as well.

> If you store it as a static asset and sync to s3, it'll be quite costly to read it on every request. An upcoming version will cache the stats file so it is read only once.

Yeah, it makes sense in dev, but in prod you'd def want to only read it once.
I've been [reading it in at runtime](https://github.com/markfinger/python-webpack/blob/development/webpack/cache.py#L12-L15), but it might make more sense to load it at startup, so that any path/serialisation errors are picked up immediately.

> Personally, I haven't run into any major integration issues but I think this approach will be frustrating for people who don't know or don't want to deal with Javascript.

Hah. Yeah, this is part of the reason why I had to build all the crappy js-host stuff. Our devs are mostly python people who cringe at the idea of JS. Personally, I feel like it introduces too much magic and too much overhead, so I'm currently musing over a replacement for much of the current stack.

I feel like we're both approaching the problem from a similar space, so it'd be good to solve all of this in a solid way.

**Comment by owais** [comment]
>> webpack-bundle-tracker will dump the first error to the stats file and django will raise that as an WebpackException so it can be noticed in the browser.

> Yeah, one thing I like about hmr is that it logs every error and warning produced. It might be worth serializing every error and then just spitting out an exception with "Webpack errors: ['...', '...']". Also, I've generally found that you can just use the error's stack property, it's something like <type>: <message> <stack>, but you'd prob need to check if it's an instance of error or just a string.

Yes. It is a simple enough thing to do but I haven't faced the need to do this yet. I was only anticipating what issues one might run into. Most of the time, you want to fix exceptions 1 by 1 in django but it wouldn't harm to show all errors in a well formatted way. I'll wait for issues raised by users before adding this. I really want to keep this lean and not add anything anything hardly would care about.


>>    sometimes when you start working after a break and django will read the already present stats file and serve the old bundles

> The stats object should have a fileDependencies array which lists every file. When I'm relying on cached content, I've been checking mtimes on every file before serving it up. If the config file or any deps have changed since the compilation, the cache throws errors and the wrapper blocks until the compiler's finished. This is a JS implementation, but it'd be pretty easy to do in python as well.

That seems to be the only sane way to do this but too complicated for my taste. I really don't want django to deal with anything other than the final generated output. The idea is to hand off everything to webpack. This is only the case when you don't run webpack and an old bundle is present. django-webpack-loader does block requests while webpack is running/compiling and responds with the latest bundle once it is compiled. I am not sure about adding support for this in django but adding `fileDepencies` to webpack-loader-plugin should be useful.

**Comment by owais** [comment]
@markfinger I ran into an issue with this today. The fact that you can't reference (require) any assets from your npm/bower components directly from your django templates as webpack doesn't load them at all.

For now, I'm working around this as mentioned here: https://github.com/webpack/file-loader/issues/15#issuecomment-139052711

**Comment by markfinger** [comment]
Hmm, I think we've got our bower_components and node_modules directories in the static file finders, so we usually just reference stuff from templates with `{% static 'some_package/...' %}`.

If you just wanted to ensure that the assets are placed into the output dir, I suppose you could manually introspect the directory with `fs` and slap them in as entries... not sure if that'd work though.
