### ISSUE TITLE
How to access hot-reloaded bundles and on-disk static files at same time?

### ISSUE THREAD

**Issue by dwjp** [owais/django-webpack-loader#55]
I have hot-reloading working as per http://owaislone.org/blog/webpack-plus-reactjs-and-django/ but since I've changed `STATIC_URL = 'http://localhost:3000/assets/bundles/'` I can no longer access other non-bundled static files.

What's the recommended approach here?

**Comment by ryanhiebert** [comment]
You shouldn't change `STATIC_URL`. If you're using the `render_bundle` template tag, it'll choose what URL to put in the tag based on your `webpack.config`. In particular, it uses the value in `config.output.PublicPath`.

So my dev webpack config has this as part of it:

```json
{
  "output": {
    "publicPath": "http://localhost:3000/static/"
  }
}
```

In my setup, I run webpack with a different config file when I'm developing. But I don't have to change any of the Django templates, because it's all in the webpack config.

**Comment by dwjp** [comment]
Ah I see, there was a comment in the aforementioned post saying `// Tell django to use this URL to load packages and not use STATIC_URL + bundle_name` and I took that to mean django had to be explicitly told where to look. Thanks for clarifying.

**Comment by owais** [comment]
@ryanhiebert Thanks
