### ISSUE TITLE
KeyError in loader.py upon error.

### ISSUE THREAD

**Issue by jleclanche** [owais/django-webpack-loader#69]
`get_bundle` defines the following:

```py
            error = u"""
            {error} in {file}
            {message}
            """.format(**assets)
```

However, upon some webpack errors, my `assets` dict contained the following:

```py
{
'file': '', 
'message': '(1,24): error TS2307: Cannot find module 'react'.', 
'status': 'error'
}
```

Therefore, django-webpack-loader crashed, shadowing the root cause of the crash. Was quite frustrating.
I can PR a simple fix that stubs `error` if it's not in there, but it seems like it's very much supposed to be in there.

**Comment by owais** [comment]
The stats/manifest file is read only for webpack-loader. It is supposed to be written to only by webpack and read by django. Django should never write to it.

**Comment by jleclanche** [comment]
The error is on read.

**Comment by owais** [comment]
OK. I suspect you are using webpack config wrong. You should use `path` option to specify the directory webpack should write to and use `filename` to specify the name of the file. You are getting wrong results because you are using `filename` where you should be using `path`.  Check webpack documentation: https://webpack.github.io/docs/configuration.html

**Comment by owais** [comment]
Please disregard to previous message. I thought I was replying to something else.

**Comment by owais** [comment]
@jleclanche This seems to be an issue when using typescript. This has been reported before: https://github.com/owais/webpack-bundle-tracker/issues/12

I'd be happy to accept a PR against `webpack-bundle-tracker` to fix the root cause.
